In [24]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [25]:
df = pd.read_csv(r'C:\Users\rohit\AppData\Local\Temp\ed782995-eaa7-40d6-ba62-5aba32852b59_earth_quake_data_set.zip.b59\0fa1ac3441b877b88230b57c63034b08-4e818b64b20e508b35cff2acac93a9ff573ba64d\earthquake_dataset.csv')

In [26]:
df.head()

,title,magnitude,date_time,cdi,mmi,alert,tsunami,sig,net,nst,dmin,gap,magType,depth,latitude,longitude,location,continent,country
0,"M 7.0 - 18 km SW of Malango, Solomon Islands",7.0,22-11-2022 02:03,8,7,green,1,768,us,117,0.509,17.0,mww,14.000,-9.7963,159.596,"Malango, Solomon Islands",Oceania,Solomon Islands
1,"M 6.9 - 204 km SW of Bengkulu, Indonesia",6.9,18-11-2022 13:37,4,4,green,0,735,us,99,2.229,34.0,mww,25.000,-4.9559,100.738,"Bengkulu, Indonesia",NaN,NaN
2,M 7.0 -,7.0,12-11-2022 07:09,3,3,green,1,755,us,147,3.125,18.0,mww,579.000,-20.0508,-178.346,NaN,Oceania,Fiji
3,"M 7.3 - 205 km ESE of Neiafu, Tonga",7.3,11-11-2022 10:48,5,5,green,1,833,us,149,1.865,21.0,mww,37.000,-19.2918,-172.129,"Neiafu, Tonga",NaN,NaN
4,M 6.6 -,6.6,09-11-2022 10:14,0,2,green,1,670,us,131,4.998,27.0,mww,624.464,-25.5948,178.278,NaN,NaN,NaN

In [27]:
df=df[['depth', 'latitude', 'longitude', 'gap', 'magnitude']]

In [28]:
df.head()

     depth  latitude  longitude   gap  magnitude
0   14.000   -9.7963    159.596  17.0        7.0
1   25.000   -4.9559    100.738  34.0        6.9
2  579.000  -20.0508   -178.346  18.0        7.0
3   37.000  -19.2918   -172.129  21.0        7.3
4  624.464  -25.5948    178.278  27.0        6.6

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 782 entries, 0 to 781
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   depth      782 non-null    float64
 1   latitude   782 non-null    float64
 2   longitude  782 non-null    float64
 3   gap        782 non-null    float64
 4   magnitude  782 non-null    float64
dtypes: float64(5)
memory usage: 30.7 KB

In [30]:
features = ['depth', 'latitude', 'longitude', 'gap']
target = 'magnitude'

In [31]:
X=df[features]
y=df[target]

In [32]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [33]:
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor(n_estimators=200)
model.fit(X_train, y_train)

preds = model.predict(X_test)

In [34]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input

nn = Sequential([
    Input(shape=(X_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(16, activation='relu'),
    Dense(1)
])

nn.compile(optimizer='adam', loss='mse')

nn.fit(X_train, y_train, epochs=50, verbose=1)
preds_nn = nn.predict(X_test)

Epoch 1/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 112.7368
Epoch 2/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 21.7913
Epoch 3/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 12.1898
Epoch 4/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 8.8507
Epoch 5/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.7361
Epoch 6/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.0172
Epoch 7/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.1997
Epoch 8/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5.7940
Epoch 9/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 5.2356
Epoch 10/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4.7702
Epoch 11/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4.3612
Epoch 12/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3.9473
Epoch 13/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3.6680
Epoch 14/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3.4447
Epoch 15/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3.2482
Epoch 16/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3.1314
Epoch 17/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.9930
Epoch 18/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2.7364
Epoch 19/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.7092
Epoch 20/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.6850
Epoch 21/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.6009
Epoch 22/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2.4773
Epoch 23/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.4061
Epoch 24/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.3103
Epoch 25/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.2453
Epoch 26/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.2151
Epoch 27/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.1719
Epoch 28/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.0899
Epoch 29/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.9706
Epoch 30/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.9923
Epoch 31/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.9241
Epoch 32/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.8839
Epoch 33/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.8326
Epoch 34/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.7680
Epoch 35/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.8049
Epoch 36/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.8428
Epoch 37/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.9440
Epoch 38/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.7494
Epoch 39/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.8657
Epoch 40/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.8645
Epoch 41/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.5899
Epoch 42/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.6014
Epoch 43/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.5441
Epoch 44/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.5686
Epoch 45/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.4993
Epoch 46/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.5607
Epoch 47/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.4794
Epoch 48/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.4810
Epoch 49/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.6648
Epoch 50/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.4757
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step

In [35]:
from sklearn.metrics import mean_absolute_error, r2_score, mean_squared_error
print("MAE:", mean_absolute_error(y_test, preds))
print("R2 Score:", r2_score(y_test, preds))
print("MSE:", mean_squared_error(y_test, preds))

MAE: 0.33496496815286686
R2 Score: -0.23370660391713538
MSE: 0.170323484649682

In [ ]:
sample =pd.DataFrame([[10.5, 28.6, 77.2, 0.8]], columns=['depth', 'latitude', 'longitude', 'gap'])
prediction = model.predict(sample)
print(prediction)  
prediction_nn = nn.predict(sample)
print(prediction_nn)
prediction_final = (prediction + prediction_nn.flatten()) / 2
print(prediction_final)

[7.2605]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
[[4.5659885]]
[5.91324427]