In [2]:
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [3]:
df=sns.load_dataset('tips')

In [4]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [5]:
df.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [6]:
df['sex'].value_counts()

sex
Male      157
Female     87
Name: count, dtype: int64

In [7]:
df['day'].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [8]:
## independent and dependent features
x=df.drop('total_bill',axis=1)
y=df['total_bill']

In [9]:
##train test split
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [11]:
x_train.head()

      tip   sex smoker   day    time  size
228  2.72  Male     No   Sat  Dinner     2
208  2.03  Male    Yes   Sat  Dinner     2
96   4.00  Male    Yes   Fri  Dinner     2
167  4.50  Male     No   Sun  Dinner     4
84   2.03  Male     No  Thur   Lunch     2

In [13]:
from sklearn.preprocessing import LabelEncoder
le1=LabelEncoder()
le2=LabelEncoder()
le3=LabelEncoder()

In [14]:
x_train['sex']=le1.fit_transform(x_train['sex'])
x_train['smoker']=le2.fit_transform(x_train['smoker'])  
x_train['time']=le3.fit_transform(x_train['time'])

In [15]:
x_train.head()

      tip  sex  smoker   day  time  size
228  2.72    1       0   Sat     0     2
208  2.03    1       1   Sat     0     2
96   4.00    1       1   Fri     0     2
167  4.50    1       0   Sun     0     4
84   2.03    1       0  Thur     1     2

In [16]:
x_test['sex']=le1.fit_transform(x_test  ['sex'])
x_test['smoker']=le2.fit_transform(x_test['smoker'])    
x_test['time']=le3.fit_transform(x_test['time'])

In [17]:
## onehot encoding
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [19]:
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1,3])],remainder='passthrough')
x_train=np.array(ct.fit_transform(x_train))
x_test=np.array(ct.transform(x_test))

In [24]:
from sklearn.svm import SVR
svr=SVR()
svr.fit(x_train,y_train)
y_pred=svr.predict(x_test)
from sklearn.metrics import r2_score,mean_absolute_error
r2_score(y_test,y_pred)

0.546786553460619

In [22]:
x_test

array([[0.  , 1.  , 0.  , 1.  , 0.  , 0.  , 3.18, 0.  , 0.  , 2.  ],
       [0.  , 1.  , 0.  , 0.  , 1.  , 0.  , 2.  , 0.  , 0.  , 2.  ],
       [0.  , 1.  , 0.  , 0.  , 1.  , 0.  , 2.  , 0.  , 0.  , 4.  ],
       [0.  , 1.  , 0.  , 1.  , 0.  , 0.  , 5.16, 1.  , 0.  , 4.  ],
       [1.  , 0.  , 0.  , 0.  , 0.  , 1.  , 2.  , 1.  , 1.  , 2.  ],
       [0.  , 1.  , 0.  , 0.  , 1.  , 0.  , 2.  , 1.  , 0.  , 2.  ],
       [0.  , 1.  , 0.  , 0.  , 0.  , 1.  , 2.56, 1.  , 1.  , 2.  ],
       [1.  , 0.  , 0.  , 0.  , 0.  , 1.  , 2.52, 0.  , 1.  , 2.  ],
       [0.  , 1.  , 0.  , 0.  , 1.  , 0.  , 3.23, 0.  , 0.  , 2.  ],
       [1.  , 0.  , 1.  , 0.  , 0.  , 0.  , 3.  , 1.  , 0.  , 2.  ],
       [0.  , 1.  , 0.  , 0.  , 1.  , 0.  , 3.  , 0.  , 0.  , 2.  ],
       [0.  , 1.  , 0.  , 1.  , 0.  , 0.  , 1.47, 0.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 0.  , 0.  , 1.  , 1.5 , 0.  , 1.  , 2.  ],
       [0.  , 1.  , 0.  , 0.  , 1.  , 0.  , 2.  , 1.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 0.  , 0.  , 1.  , 1.83, 0.  , 1.  , 1.  ],
       [1.  , 0.  , 0.  , 0.  , 0.  , 1.  , 1.36, 0.  , 1.  , 3.  ],
       [0.  , 1.  , 0.  , 0.  , 0.  , 1.  , 4.  , 1.  , 1.  , 3.  ],
       [0.  , 1.  , 0.  , 0.  , 1.  , 0.  , 3.92, 0.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 1.  , 0.  , 0.  , 2.47, 0.  , 0.  , 2.  ],
       [0.  , 1.  , 0.  , 0.  , 0.  , 1.  , 5.  , 0.  , 1.  , 5.  ],
       [1.  , 0.  , 0.  , 1.  , 0.  , 0.  , 2.45, 0.  , 0.  , 4.  ],
       [0.  , 1.  , 0.  , 1.  , 0.  , 0.  , 3.35, 0.  , 0.  , 3.  ],
       [1.  , 0.  , 0.  , 1.  , 0.  , 0.  , 4.  , 1.  , 0.  , 2.  ],
       [0.  , 1.  , 0.  , 1.  , 0.  , 0.  , 1.45, 0.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 0.  , 1.  , 0.  , 3.5 , 1.  , 0.  , 3.  ],
       [0.  , 1.  , 0.  , 0.  , 0.  , 1.  , 2.31, 0.  , 1.  , 2.  ],
       [0.  , 1.  , 0.  , 0.  , 1.  , 0.  , 1.71, 0.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 1.  , 0.  , 0.  , 5.  , 1.  , 0.  , 2.  ],
       [0.  , 1.  , 0.  , 0.  , 1.  , 0.  , 2.  , 0.  , 0.  , 4.  ],
       [0.  , 1.  , 0.  , 0.  , 1.  , 0.  , 5.  , 0.  , 0.  , 6.  ],
       [0.  , 1.  , 0.  , 0.  , 1.  , 0.  , 4.  , 0.  , 0.  , 3.  ],
       [0.  , 1.  , 0.  , 1.  , 0.  , 0.  , 1.44, 1.  , 0.  , 2.  ],
       [0.  , 1.  , 0.  , 1.  , 0.  , 0.  , 2.34, 0.  , 0.  , 4.  ],
       [0.  , 1.  , 0.  , 1.  , 0.  , 0.  , 3.21, 1.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 0.  , 1.  , 0.  , 3.5 , 0.  , 0.  , 3.  ],
       [1.  , 0.  , 0.  , 0.  , 0.  , 1.  , 2.92, 0.  , 1.  , 4.  ],
       [0.  , 1.  , 1.  , 0.  , 0.  , 0.  , 1.5 , 1.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 0.  , 0.  , 1.  , 5.  , 1.  , 1.  , 4.  ],
       [1.  , 0.  , 0.  , 0.  , 0.  , 1.  , 2.75, 0.  , 1.  , 2.  ],
       [0.  , 1.  , 0.  , 1.  , 0.  , 0.  , 2.  , 1.  , 0.  , 2.  ],
       [0.  , 1.  , 0.  , 1.  , 0.  , 0.  , 1.25, 0.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 0.  , 0.  , 1.  , 2.  , 0.  , 1.  , 2.  ],
       [0.  , 1.  , 0.  , 0.  , 1.  , 0.  , 2.55, 0.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 0.  , 1.  , 0.  , 1.67, 0.  , 0.  , 3.  ],
       [0.  , 1.  , 0.  , 0.  , 0.  , 1.  , 2.  , 1.  , 1.  , 2.  ],
       [1.  , 0.  , 0.  , 1.  , 0.  , 0.  , 1.  , 1.  , 0.  , 1.  ],
       [1.  , 0.  , 0.  , 1.  , 0.  , 0.  , 1.61, 1.  , 0.  , 2.  ],
       [0.  , 1.  , 0.  , 1.  , 0.  , 0.  , 2.31, 0.  , 0.  , 3.  ],
       [0.  , 1.  , 0.  , 0.  , 0.  , 1.  , 1.44, 0.  , 1.  , 2.  ]])

In [25]:
print(mean_absolute_error(y_test,y_pred))

4.439210101429987

In [26]:
from sklearn.model_selection import GridSearchCV
param_grid={'C':[0.1,1,10,100],'gamma':[1,0.1,0.01,0.001],'kernel':['rbf']}
grid=GridSearchCV(SVR(),param_grid,refit=True,verbose=2)
grid.fit(x_train,y_train)
y_pred=grid.predict(x_test)
r2_score(y_test,y_pred)

Fitting 5 folds for each of 16 candidates, totalling 80 fits
[CV] END .........................C=0.1, gamma=1, kernel=rbf; total time=   0.0s
[CV] END .........................C=0.1, gamma=1, kernel=rbf; total time=   0.0s
[CV] END .........................C=0.1, gamma=1, kernel=rbf; total time=   0.0s
[CV] END .........................C=0.1, gamma=1, kernel=rbf; total time=   0.0s
[CV] END .........................C=0.1, gamma=1, kernel=rbf; total time=   0.0s
[CV] END .......................C=0.1, gamma=0.1, kernel=rbf; total time=   0.0s
[CV] END .......................C=0.1, gamma=0.1, kernel=rbf; total time=   0.0s
[CV] END .......................C=0.1, gamma=0.1, kernel=rbf; total time=   0.0s
[CV] END .......................C=0.1, gamma=0.1, kernel=rbf; total time=   0.0s
[CV] END .......................C=0.1, gamma=0.1, kernel=rbf; total time=   0.0s
[CV] END ......................C=0.1, gamma=0.01, kernel=rbf; total time=   0.0s
[CV] END ......................C=0.1, gamma=0.01, kernel=rbf; total time=   0.0s
[CV] END ......................C=0.1, gamma=0.01, kernel=rbf; total time=   0.0s
[CV] END ......................C=0.1, gamma=0.01, kernel=rbf; total time=   0.0s
[CV] END ......................C=0.1, gamma=0.01, kernel=rbf; total time=   0.0s
[CV] END .....................C=0.1, gamma=0.001, kernel=rbf; total time=   0.0s
[CV] END .....................C=0.1, gamma=0.001, kernel=rbf; total time=   0.0s
[CV] END .....................C=0.1, gamma=0.001, kernel=rbf; total time=   0.0s
[CV] END .....................C=0.1, gamma=0.001, kernel=rbf; total time=   0.0s
[CV] END .....................C=0.1, gamma=0.001, kernel=rbf; total time=   0.0s
[CV] END ...........................C=1, gamma=1, kernel=rbf; total time=   0.0s
[CV] END ...........................C=1, gamma=1, kernel=rbf; total time=   0.0s
[CV] END ...........................C=1, gamma=1, kernel=rbf; total time=   0.0s
[CV] END ...........................C=1, gamma=1, kernel=rbf; total time=   0.0s
[CV] END ...........................C=1, gamma=1, kernel=rbf; total time=   0.0s
[CV] END .........................C=1, gamma=0.1, kernel=rbf; total time=   0.0s
[CV] END .........................C=1, gamma=0.1, kernel=rbf; total time=   0.0s
[CV] END .........................C=1, gamma=0.1, kernel=rbf; total time=   0.0s
[CV] END .........................C=1, gamma=0.1, kernel=rbf; total time=   0.0s
[CV] END .........................C=1, gamma=0.1, kernel=rbf; total time=   0.0s
[CV] END ........................C=1, gamma=0.01, kernel=rbf; total time=   0.0s
[CV] END ........................C=1, gamma=0.01, kernel=rbf; total time=   0.0s
[CV] END ........................C=1, gamma=0.01, kernel=rbf; total time=   0.0s
[CV] END ........................C=1, gamma=0.01, kernel=rbf; total time=   0.0s
[CV] END ........................C=1, gamma=0.01, kernel=rbf; total time=   0.0s
[CV] END .......................C=1, gamma=0.001, kernel=rbf; total time=   0.0s
[CV] END .......................C=1, gamma=0.001, kernel=rbf; total time=   0.0s
[CV] END .......................C=1, gamma=0.001, kernel=rbf; total time=   0.0s
[CV] END .......................C=1, gamma=0.001, kernel=rbf; total time=   0.0s
[CV] END .......................C=1, gamma=0.001, kernel=rbf; total time=   0.0s
[CV] END ..........................C=10, gamma=1, kernel=rbf; total time=   0.0s
[CV] END ..........................C=10, gamma=1, kernel=rbf; total time=   0.0s
[CV] END ..........................C=10, gamma=1, kernel=rbf; total time=   0.0s
[CV] END ..........................C=10, gamma=1, kernel=rbf; total time=   0.0s
[CV] END ..........................C=10, gamma=1, kernel=rbf; total time=   0.0s
[CV] END ........................C=10, gamma=0.1, kernel=rbf; total time=   0.0s
[CV] END ........................C=10, gamma=0.1, kernel=rbf; total time=   0.0s
[CV] END ........................C=10, gamma=0.1, kernel=rbf; total time=   0.0s
[CV] END ........................C=10, gamma=0.1, kernel=rbf; total time=   0.0s
[CV] END ........................C=10, gamma=0.1, kernel=rbf; total time=   0.0s
[CV] END .......................C=10, gamma=0.01, kernel=rbf; total time=   0.0s
[CV] END .......................C=10, gamma=0.01, kernel=rbf; total time=   0.0s
[CV] END .......................C=10, gamma=0.01, kernel=rbf; total time=   0.0s
[CV] END .......................C=10, gamma=0.01, kernel=rbf; total time=   0.0s
[CV] END .......................C=10, gamma=0.01, kernel=rbf; total time=   0.0s
[CV] END ......................C=10, gamma=0.001, kernel=rbf; total time=   0.0s
[CV] END ......................C=10, gamma=0.001, kernel=rbf; total time=   0.0s
[CV] END ......................C=10, gamma=0.001, kernel=rbf; total time=   0.0s
[CV] END ......................C=10, gamma=0.001, kernel=rbf; total time=   0.0s
[CV] END ......................C=10, gamma=0.001, kernel=rbf; total time=   0.0s
[CV] END .........................C=100, gamma=1, kernel=rbf; total time=   0.0s
[CV] END .........................C=100, gamma=1, kernel=rbf; total time=   0.0s
[CV] END .........................C=100, gamma=1, kernel=rbf; total time=   0.0s
[CV] END .........................C=100, gamma=1, kernel=rbf; total time=   0.0s
[CV] END .........................C=100, gamma=1, kernel=rbf; total time=   0.0s
[CV] END .......................C=100, gamma=0.1, kernel=rbf; total time=   0.0s
[CV] END .......................C=100, gamma=0.1, kernel=rbf; total time=   0.0s
[CV] END .......................C=100, gamma=0.1, kernel=rbf; total time=   0.0s
[CV] END .......................C=100, gamma=0.1, kernel=rbf; total time=   0.0s
[CV] END .......................C=100, gamma=0.1, kernel=rbf; total time=   0.0s
[CV] END ......................C=100, gamma=0.01, kernel=rbf; total time=   0.0s
[CV] END ......................C=100, gamma=0.01, kernel=rbf; total time=   0.0s
[CV] END ......................C=100, gamma=0.01, kernel=rbf; total time=   0.0s
[CV] END ......................C=100, gamma=0.01, kernel=rbf; total time=   0.0s
[CV] END ......................C=100, gamma=0.01, kernel=rbf; total time=   0.0s
[CV] END .....................C=100, gamma=0.001, kernel=rbf; total time=   0.0s
[CV] END .....................C=100, gamma=0.001, kernel=rbf; total time=   0.0s
[CV] END .....................C=100, gamma=0.001, kernel=rbf; total time=   0.0s
[CV] END .....................C=100, gamma=0.001, kernel=rbf; total time=   0.0s
[CV] END .....................C=100, gamma=0.001, kernel=rbf; total time=   0.0s

0.6225720733563593

In [27]:
grid.best_params_

{'C': 100, 'gamma': 0.01, 'kernel': 'rbf'}

In [28]:
grid_pred=grid.predict(x_test)
r2_score(y_test,grid_pred)
print(mean_absolute_error(y_test,grid_pred))

4.1194001790050745